#!/usr/bin/env python3
"""Canonical semantics v2 reference package.

This package is the decisive v2 semantic universe on the Python side.
`theory/spec/canonical_semantics.py` remains the v1 compatibility entry;
v1 never gains v2 decisive status. Names, field semantics, and enums are
aligned with the Lean registry through the machine-readable manifest in
`manifest.py`; Python serializable contracts do not take Lean-definition
authority.
"""

from .kernel import (
    ApplicableNormQuery,
    CandidateState,
    Disposition,
    EffectType,
    Event,
    EventHistory,
    EvalResult,
    Judgment,
    JudgmentEvent,
    Jurisdiction,
    JurisdictionRoute,
    KernelState,
    LegalPower,
    NormState,
    NormVersion,
    Question,
    QuestionKind,
    Relation,
    SharedConstraint,
    SharedConstraintKind,
    applicable_norm,
    eval_batch,
    eval_question,
    narrow_candidates,
    transfer,
)
from .manifest import (
    ENUM_REGISTRY,
    MANIFEST_SCHEMA,
    TYPE_LAYERS,
    V1_CANONICAL_TYPES,
    build_manifest,
    canonical_v2_type_names,
)
from .migration import migrate_v1_payload
from .types import (
    AttackKind,
    AuthorityLevel,
    BackendKind,
    DecisionStatus,
    FailureStatus,
    GateStatus,
    IdKind,
    Modality,
    RuleKind,
    TypedId,
    canonical_collection,
    canonical_digest,
    canonical_json,
)

__all__ = [
    "ApplicableNormQuery",
    "AttackKind",
    "AuthorityLevel",
    "BackendKind",
    "CandidateState",
    "DecisionStatus",
    "Disposition",
    "ENUM_REGISTRY",
    "EffectType",
    "Event",
    "EventHistory",
    "EvalResult",
    "FailureStatus",
    "GateStatus",
    "IdKind",
    "Judgment",
    "JudgmentEvent",
    "Jurisdiction",
    "JurisdictionRoute",
    "KernelState",
    "LegalPower",
    "MANIFEST_SCHEMA",
    "Modality",
    "NormState",
    "NormVersion",
    "Question",
    "QuestionKind",
    "Relation",
    "RuleKind",
    "SharedConstraint",
    "SharedConstraintKind",
    "TYPE_LAYERS",
    "TypedId",
    "V1_CANONICAL_TYPES",
    "applicable_norm",
    "build_manifest",
    "canonical_collection",
    "canonical_digest",
    "canonical_json",
    "canonical_v2_type_names",
    "eval_batch",
    "eval_question",
    "migrate_v1_payload",
    "narrow_candidates",
    "transfer",
]
