import JurisLean.Genealogy.Part0
import JurisLean.Genealogy.Part1
import JurisLean.Genealogy.Part2
import JurisLean.Genealogy.Part3
import JurisLean.Genealogy.Part4
import JurisLean.Genealogy.Part5
import JurisLean.Genealogy.Part6
import JurisLean.Genealogy.General
import JurisLean.Genealogy.Boundary
import JurisLean.Genealogy.TSpectrum.Batch1
