/-!
# FullMath aggregator

Generated by `scripts/ci/check_import_reachability.py --write`; regenerate rather
than hand-edit. `lakefile.lean` declares a single library root, so without this
aggregator `lake build` never elaborates the FullMath tree while the paper still
counts its theorems (audit P1-12).
-/
import JurisLean.FullMath.Acceptance
import JurisLean.FullMath.Action.IncentiveEnumeration
import JurisLean.FullMath.Action.Mechanisms
import JurisLean.FullMath.Action.RobustDecisions
import JurisLean.FullMath.Action.Settlement
import JurisLean.FullMath.Burden.DomainAgnostic
import JurisLean.FullMath.Burden.Families
import JurisLean.FullMath.Burden.Readiness
import JurisLean.FullMath.Burden.SourceTime
import JurisLean.FullMath.Burden.Standards
import JurisLean.FullMath.Causal.PartialIdentification
import JurisLean.FullMath.CompletionAudit
import JurisLean.FullMath.Composition.CheckerCorrespondence
import JurisLean.FullMath.Composition.DomainChains
import JurisLean.FullMath.Composition.EnvelopePipeline
import JurisLean.FullMath.Composition.RelationalComposition
import JurisLean.FullMath.Composition.ScenarioBridge
import JurisLean.FullMath.Composition.UnifiedCorrectness
import JurisLean.FullMath.Contracts
import JurisLean.FullMath.Core.BusinessSemantics
import JurisLean.FullMath.Core.Foundations
import JurisLean.FullMath.Core.IdentityCodec
import JurisLean.FullMath.Document.ByteSyntax
import JurisLean.FullMath.Evidence.Admission
import JurisLean.FullMath.Evidence.Provenance
import JurisLean.FullMath.Evidence.Withdrawal
import JurisLean.FullMath.Gaps.Gaps
import JurisLean.FullMath.GenericKernels
import JurisLean.FullMath.Logic.ArgumentConstruction
import JurisLean.FullMath.Logic.ArgumentIdentity
import JurisLean.FullMath.Logic.AttackCompilation
import JurisLean.FullMath.Logic.ExtensionProfiles
import JurisLean.FullMath.Logic.HornFixpoint
import JurisLean.FullMath.Logic.QueryAggregation
import JurisLean.FullMath.Numeric.Banach
import JurisLean.FullMath.Numeric.Bellman
import JurisLean.FullMath.Numeric.Convexity
import JurisLean.FullMath.Numeric.IntegerBranch
import JurisLean.FullMath.Numeric.Intervals
import JurisLean.FullMath.Numeric.LinearPrograms
import JurisLean.FullMath.Numeric.Quantities
import JurisLean.FullMath.Probability.BetaInterval
import JurisLean.FullMath.Probability.Brier
import JurisLean.FullMath.Probability.Conditioning
import JurisLean.FullMath.Probability.DirichletPosterior
import JurisLean.FullMath.Probability.E01Contract
import JurisLean.FullMath.Probability.EvidenceIdentity
import JurisLean.FullMath.Probability.FiniteBN
import JurisLean.FullMath.Probability.Misspecification
import JurisLean.FullMath.Probability.ModelAveraging
import JurisLean.FullMath.Probability.PAV
import JurisLean.FullMath.Probability.SplitNoLeak
import JurisLean.FullMath.Probability.UnprocessedMass
import JurisLean.FullMath.Probability.VariableElimination
import JurisLean.FullMath.Representation.FiniteCertificates
import JurisLean.FullMath.Representation.SymbolicRepresentation
import JurisLean.FullMath.Roots.SevenRoots
import JurisLean.FullMath.Tranche1
import JurisLean.FullMath.Tranche2
import JurisLean.FullMath.Tranche3
import JurisLean.FullMath.Tranche4
import JurisLean.FullMath.Tranche5
import JurisLean.FullMath.Tranche6
import JurisLean.FullMath.Tranche7
