#!/usr/bin/env python3
"""Declaration-shape account: how many theorems are relabelling, and how many bind nothing.

The audit's P1-10 counted contract relabelling as a share of the declared theorems, and
both paper editions have carried two figures for it -- one-line `theorem alias : contract
:= proof` transfers, and statements that bind no variable at all. Neither figure had a
producing artifact: no script recomputed them, so they could drift with the source and no
gate would notice. That is the same class of defect the census and the duplication report
were built to close, so they get the same treatment here.

The rules are deliberately syntactic and are restated in the artifact, because "contains
no mathematics" is a judgement while "the proof term is one identifier" is not:

  ALIAS_ONE_LINER   the whole declaration is one line whose statement is a single
                    identifier and whose proof term is a single identifier
  CLOSED_NO_BINDERS between the declaration name and its conclusion colon there is no
                    binder, and the conclusion contains no `∀`

A theorem can fall in both, in one, or in neither, so these are two measurements and not a
partition. Counts are taken over the same scope the closure census uses, and the total is
cross-checked against `trivial_proof_census.json` so the two cannot describe different
trees.

    python scripts/ci/generate_declaration_shape_report.py            # write
    python scripts/ci/generate_declaration_shape_report.py --check    # fail if stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_trivial_proof_census import (  # noqa: E402
    SCAN_DIR, blocks, strip_comments, tracked_lean,
)

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "formal-release" / "declaration_shape_report.json"
CENSUS = ROOT / "docs" / "formal-release" / "trivial_proof_census.json"
SCHEMA = "declaration-shape-report-v1"
STATUS = "source_shape_report_not_a_judgement_about_content"
RULES = {
    "ALIAS_ONE_LINER": (
        "single-line theorem whose conclusion is one identifier and whose proof term is "
        "one identifier, i.e. `theorem name : contract := proof`"
    ),
    "CLOSED_NO_BINDERS": (
        "theorem that declares no binders before its conclusion colon -- no parentheses, "
        "braces or brackets -- and whose text contains no forall or lambda binder in "
        "either spelling, i.e. the statement is about concrete data"
    ),
}
AUTHORITY = (
    "Generated by scripts/ci/generate_declaration_shape_report.py from tracked Lean source, "
    "reusing the declaration splitter of the closure census. It is a text measurement over "
    "the tracked tree at the recorded subject; it is not Lean-compiler evidence, and it does "
    "not judge whether a proposition is worth having."
)

FORALLISH = re.compile(r"∀|\bforall\b|\bfun\b|Π")


ALIAS = re.compile(
    r"^theorem\s+[^\s(:]+\s*:\s*[A-Za-z0-9_.']+\s*:?=\s*[A-Za-z0-9_.']+$"
)


def shape_of(block: str) -> list[str]:
    """Which of the two declared rules this declaration block satisfies."""
    one_line = " ".join(block.split())
    tags = []
    if ALIAS.match(one_line):
        tags.append("ALIAS_ONE_LINER")
    head = _conclusion_head(one_line)
    if (
        head is not None
        and not any(ch in head for ch in "({[")
        and not FORALLISH.search(one_line)
    ):
        tags.append("CLOSED_NO_BINDERS")
    return tags


def _conclusion_head(one_line: str):
    """Text between the declaration name and the first depth-0 conclusion colon."""
    body = one_line.split(None, 1)[1] if len(one_line.split(None, 1)) > 1 else ""
    depth = 0
    for i, ch in enumerate(body):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == ":" and depth == 0 and body[i:i + 2] != ":=":
            return body[:i]
    return None


def build() -> dict:
    pkg: dict[str, int] = {"ALIAS_ONE_LINER": 0, "CLOSED_NO_BINDERS": 0, "theorems": 0}
    per_file: dict[str, dict[str, int]] = {}
    for path in tracked_lean():
        abs_path = Path(path) if Path(path).is_absolute() else ROOT / path
        rel = abs_path.relative_to(ROOT).as_posix()
        code = strip_comments(abs_path.read_text(encoding="utf-8"))
        file_counts = {"ALIAS_ONE_LINER": 0, "CLOSED_NO_BINDERS": 0, "theorems": 0}
        for _name, block in blocks(code):
            tags = shape_of(block)
            pkg["theorems"] += 1
            file_counts["theorems"] += 1
            for tag in tags:
                pkg[tag] += 1
                file_counts[tag] += 1
        if file_counts["theorems"]:
            per_file[rel] = file_counts
    census = json.loads(CENSUS.read_text(encoding="utf-8"))
    if census["theorem_declarations"] != pkg["theorems"]:
        raise SystemExit(
            f"scope disagreement: census sees {census['theorem_declarations']} theorems, "
            f"this report sees {pkg['theorems']} -- the two parsers no longer agree"
        )
    return {
        "schema_version": SCHEMA,
        "status": STATUS,
        "generated_by": "python scripts/ci/generate_declaration_shape_report.py",
        "authority_note": AUTHORITY,
        "rules": RULES,
        "subject_binding_source": (
            "This report is a pure text measurement, so it deliberately records no commit: "
            "an artifact that names the commit which introduces it can never verify against "
            "that commit. The subject and per-file hashes that bind it live in "
            "theorem_inventory_v3.json, which this report is cross-checked against."
        ),
        "cross_check": {
            "census_theorem_declarations": census["theorem_declarations"],
            "this_report_package_theorems": pkg["theorems"],
            "agree": True,
        },
        "scope": {
            "walked_tree": SCAN_DIR,
            "counts": pkg,
            "scope_note": (
                "Same file set the closure census walks, i.e. the JurisLean package tree; "
                "draft artifacts outside it are not measured here."
            ),
        },
        "note": (
            "The two classes overlap, so they are not a partition and may not be added. "
            "Counts describe the tracked tree at `subject`; later commits do not inherit them."
        ),
    }


def render(doc: dict) -> str:
    return json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the artifact is stale")
    args = ap.parse_args()
    doc = build()
    text = render(doc)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("declaration shape report is stale; regenerate it", file=sys.stderr)
            return 1
        print("declaration shape report ok")
        return 0
    OUT.write_text(text, encoding="utf-8")
    counts = doc["scope"]["counts"]
    print(
        f"wrote {OUT.relative_to(ROOT)}: alias_one_liner={counts['ALIAS_ONE_LINER']} "
        f"closed_no_binders={counts['CLOSED_NO_BINDERS']} of {counts['theorems']} theorems"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
