#!/usr/bin/env python3
"""Census of how each Lean theorem in the package is closed.

The audit's P1-10 said a quarter of the declared theorems are contract relabelling
rather than mathematics, and the repository's answer so far graded only the 133
T-spectrum carriers -- the other ~1750 declarations were unmeasured, and the report's
UNKNOWN list named exactly that gap (no repo-wide targeted scan of reflexivity-closed
proofs). This generates that scan: every `theorem` in `JurisLean/` is split into its
declaration block, and the block's closing term is classified.

Categories are deliberately mechanical, and the word "trivial" is a statement about
the *proof term*, not about the proposition:

  TRIVIAL_TERM   closed by `rfl`, `Iff.rfl`, `trivial`, `True.intro`, or a pure
                 `by rfl` / `by trivial` block -- no tactic beyond reflexivity
  DECIDE_CLOSED  closed by `decide`/`native_decide`/`simp`+`decide` only
  TACTIC         anything else

`TRIVIAL_TERM` is the count a paper must not present as a proved theorem of substance,
and `DECIDE_CLOSED` is the ground-literal class. The census is a claim about source
shape; whether a statement is worth having is a separate judgement this does not make.

    python scripts/ci/generate_trivial_proof_census.py            # write
    python scripts/ci/generate_trivial_proof_census.py --check     # fail if stale
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "formal-release" / "trivial_proof_census.json"
SCAN_DIR = "proofs/lean/juris_lean/JurisLean"
SCHEMA = "trivial-proof-census-v1"
STATUS = "source_shape_census_not_a_judgement_about_content"
AUTHORITY = (
    "Generated by scripts/ci/generate_trivial_proof_census.py from tracked Lean source. "
    "It classifies the closing proof term of each theorem declaration; it does not say "
    "whether a proposition is worth proving, and it is not Lean-compiler evidence."
)

THEOREM_HEAD = re.compile(r"^(?:@\[[^\]]*\][ \t]*)*theorem\s+([^\s(:{]+)")
KEYWORD_HEAD = re.compile(
    r"^(?:@\[[^\]]*\][ \t]*)*(?:theorem|lemma|def|structure|inductive|instance|class|abbrev|example)\b"
)
TRIVIAL_CLOSERS = (
    re.compile(r"^[=:]\s*(?:Iff\.rfl|rfl|trivial|True\.intro)\b"),
    re.compile(r"^[=:]\s*by\s+(?:rfl|trivial|exact rfl|exact Iff\.rfl)\s*$"),
    re.compile(r"^by\s+(?:rfl|trivial|exact rfl|exact Iff\.rfl)\s*$"),
)
DECIDE_CLOSERS = (
    re.compile(r"^[=:]\s*(?:by\s+)?decide\s*$"),
    re.compile(r"^by\s+decide\s*$"),
)


def strip_comments(text: str) -> str:
    """Reuse the repository's comment state machine so commented proofs do not count."""

    try:
        from scripts.scan_lean_guards import strip_comments as one_line
    except ImportError:  # run as `python scripts/ci/<this>.py`: sys.path[0] is scripts/ci
        sys.path.insert(0, str(ROOT / "scripts"))
        from scan_lean_guards import strip_comments as one_line
    out = []
    depth = 0
    for line in text.splitlines():
        code, depth = one_line(line, depth)
        out.append(code)
    return "\n".join(out)


def blocks(code: str) -> list[tuple[str, str]]:
    """(name, block text) per theorem declaration, up to the next declaration."""

    lines = code.splitlines()
    heads = [(i, m.group(1)) for i, line in enumerate(lines) if (m := THEOREM_HEAD.match(line))]
    out = []
    for pos, (start, name) in enumerate(heads):
        stop = heads[pos + 1][0] if pos + 1 < len(heads) else len(lines)
        # cut at any non-theorem declaration inside the span
        for j in range(start + 1, stop):
            if KEYWORD_HEAD.match(lines[j]) and not THEOREM_HEAD.match(lines[j]):
                stop = j
                break
        out.append((name, "\n".join(lines[start:stop])))
    return out


TRIVIAL_TERM_RE = re.compile(r"^(?:Iff\.rfl|rfl|trivial|True\.intro|Eq\.refl\s+\S+|⟨\s*rfl\s*,\s*rfl\s*⟩)$")
TRIVIAL_BY_RE = re.compile(r"^by\s+(?:rfl|trivial|exact\s+(?:Iff\.)?rfl|simp)$")
DECIDE_RE = re.compile(r"^(?:by\s+)?(?:decide|native_decide)$")


def proof_part(block: str) -> str:
    """Everything after the statement's `:=` or its trailing `by`."""

    if ":=" in block:
        return block.split(":=", 1)[1]
    m = re.search(r"\bby\b", block)
    return block[m.start():] if m else ""


def classify(block: str) -> str:
    proof = " ".join(proof_part(block).split())
    if TRIVIAL_TERM_RE.match(proof) or TRIVIAL_BY_RE.match(proof):
        return "TRIVIAL_TERM"
    if DECIDE_RE.match(proof):
        return "DECIDE_CLOSED"
    return "TACTIC"


def tracked_lean() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z", "--", SCAN_DIR],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace", check=True,
    ).stdout
    return [Path(p) for p in out.split("\0") if p.endswith(".lean")]


def build() -> dict:
    per_file = {}
    counts = {"TRIVIAL_TERM": 0, "DECIDE_CLOSED": 0, "TACTIC": 0}
    trivial_names = []
    for path in tracked_lean():
        code = strip_comments(path.read_text(encoding="utf-8", errors="replace"))
        rows = []
        for name, block in blocks(code):
            kind = classify(block)
            counts[kind] += 1
            rows.append({"name": name, "closure": kind})
            if kind == "TRIVIAL_TERM":
                trivial_names.append(f"{path.as_posix()}::{name}")
        if rows:
            per_file[path.as_posix()] = rows
    total = sum(len(v) for v in per_file.values())
    return {
        "schema_version": SCHEMA,
        "status": STATUS,
        "authority_note": AUTHORITY,
        "generated_by": "python scripts/ci/generate_trivial_proof_census.py",
        "theorem_declarations": total,
        "closure_counts": counts,
        "trivial_term_declarations": sorted(trivial_names),
        "per_file": {k: v for k, v in sorted(per_file.items())},
    }


def render(doc: dict) -> str:
    return json.dumps(doc, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if the committed census is stale")
    args = ap.parse_args()

    doc = build()
    text = render(doc)
    if args.check:
        if not OUT.exists():
            print("missing docs/formal-release/trivial_proof_census.json", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print("trivial_proof_census.json is stale", file=sys.stderr)
            return 1
        print(
            f"census ok: {doc['theorem_declarations']} theorems, "
            f"closure {doc['closure_counts']}"
        )
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({doc['theorem_declarations']} theorems) {doc['closure_counts']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
