"""T-spectrum coverage ledger gates (schema v2, generated artifact).

Qoder audit P0-1 and P0-2 came from this ledger being hand-written: all 127
rows claimed ``FULL`` while 124 of them named no theorem at all, and one row
anchored the two-sentencing-track target (T112) to an interpretation-constructor
theorem that also served T122. The previous gate made that uncatchable by
hard-coding ``(covered, open) == (127, 0)``.

These gates therefore check the ledger against the thing it claims to describe:
the ``namespace T##`` blocks in ``JurisLean/Genealogy/TSpectrum/``.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "ci"))

import generate_t_coverage_ledger as gen  # noqa: E402

LEDGER = ROOT / "theory" / "spec" / "lh_alignment" / "t_p_coverage.jsonl"
PAPER_CN = ROOT / "docs" / "paper-rewrite" / "paper_cn.md"
LEAN_BASE = ROOT / "proofs" / "lean" / "juris_lean"

VALID_GRADES = {"GENERAL", "DEF_PROJECTION", "WITNESS"}
VALID_RELATIONS = {"EXACT", "SPECIALIZATION"}


def _rows() -> list[dict]:
    return [
        json.loads(line)
        for line in LEDGER.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def _module_path(module: str) -> Path:
    return LEAN_BASE / (module.replace(".", "/") + ".lean")


def test_exactly_127_real_t_each_once() -> None:
    rows = _rows()
    ids = [r["t_id"] for r in rows]
    assert ids == [f"T{i:02d}" if i < 10 else f"T{i}" for i in range(1, 128)]
    assert len(set(ids)) == 127


def test_ledger_is_what_the_lean_sources_imply() -> None:
    """No hand-editing: the file must equal the generated bytes."""
    assert LEDGER.read_text(encoding="utf-8") == gen.serialize(gen.build_rows())


def test_every_anchor_resolves_to_a_real_theorem() -> None:
    """P0-1: a COVERED row may not name null and may not name a missing theorem."""
    for r in _rows():
        assert r["p_coverage"], r["t_id"]
        for c in r["p_coverage"]:
            assert c.get("theorem"), f"{r['t_id']} claims {c['coverage']} with no theorem"
            src = _module_path(c["module"])
            assert src.exists(), f"{r['t_id']}: module does not exist: {c['module']}"
            text = src.read_text(encoding="utf-8")
            assert re.search(r"^theorem " + re.escape(c["theorem"]) + r"\b", text, re.M), (
                f"{r['t_id']}: theorem {c['theorem']} not found in {c['module']}"
            )


def test_carrier_grade_matches_the_anchored_block() -> None:
    """A row may not upgrade its own grade away from what the proof does."""
    for r in _rows():
        for c in r["p_coverage"]:
            assert c["proof_grade"] in VALID_GRADES, (r["t_id"], c)
            assert c["relation"] in VALID_RELATIONS, (r["t_id"], c)
            if c["relation"] != "EXACT":
                continue
            src = _module_path(c["module"])
            text = src.read_text(encoding="utf-8")
            block = re.search(
                r"^namespace " + re.escape(r["t_id"]) + r"\n(.*?)^end " + re.escape(r["t_id"]) + r"$",
                text,
                re.M | re.S,
            )
            assert block, f"{r['t_id']} not found in {c['module']}"
            body = re.search(
                r"^theorem " + re.escape(c["theorem"]) + r"\b(.*?)(?=^theorem |^end |\Z)",
                block.group(1),
                re.M | re.S,
            )
            assert body, f"{r['t_id']}: cannot re-read carrier {c['theorem']}"
            assert gen.grade_theorem(block.group(1)[body.start():]) == c["proof_grade"], (
                f"{r['t_id']}: recorded grade {c['proof_grade']} disagrees with the source"
            )


def test_no_theorem_serves_two_t_targets() -> None:
    """P0-2: T112/T122 used to share one anchor."""
    seen: dict[tuple[str, str], str] = {}
    for r in _rows():
        for c in r["p_coverage"]:
            key = (c["module"], c["theorem"])
            assert key not in seen, (
                f"{key} anchors both {seen.get(key)} and {r['t_id']}"
            )
            seen[key] = r["t_id"]


def test_false_sentencing_anchor_stays_removed() -> None:
    t112 = next(r for r in _rows() if r["t_id"] == "T112")
    assert all(
        c["theorem"] != "isolated_branch_preserved" for c in t112["p_coverage"]
    ), "T112 (量刑双线) must not be carried by the interpretation-branch theorem"


def test_full_coverage_requires_a_clean_general_carrier() -> None:
    for r in _rows():
        exact = [c for c in r["p_coverage"] if c["relation"] == "EXACT"]
        if all(c["coverage"] == "FULL" for c in exact):
            assert not r["downgrade_noted"], r["t_id"]
            assert all(c["proof_grade"] == "GENERAL" for c in exact), r["t_id"]


def test_recorded_counts_match_derived_counts() -> None:
    """The number the paper quotes is derived here, never typed into a gate."""
    rows = _rows()
    full = sum(
        1
        for r in rows
        if all(c["coverage"] == "FULL" for c in r["p_coverage"] if c["relation"] == "EXACT")
    )
    carried = sum(1 for r in rows if r["status"] == "COVERED")
    assert carried == 127
    assert full == sum(
        1
        for r in rows
        if r["downgrade_noted"] is False
        and all(
            c["proof_grade"] == "GENERAL"
            for c in r["p_coverage"]
            if c["relation"] == "EXACT"
        )
    )


def test_open_rows_state_a_reason() -> None:
    for r in _rows():
        if r["status"] == "OPEN":
            assert r["open_reason"], r["t_id"]
        if any(c["coverage"] != "FULL" for c in r["p_coverage"] if c["relation"] == "EXACT"):
            assert r["open_reason"], f"{r['t_id']} is not FULL but records no gap"


def test_python_assets_exist_and_are_not_carriers() -> None:
    for r in _rows():
        for rel in r["python_assets"]:
            assert (ROOT / rel).exists(), f"{r['t_id']}: python asset missing: {rel}"
        carrier_modules = {c["module"] for c in r["p_coverage"]}
        assert all(m.startswith("JurisLean.") for m in carrier_modules), r["t_id"]


def test_downgrade_markers_are_copied_not_invented() -> None:
    for r in _rows():
        src = ROOT / r["carrier_file"]
        text = src.read_text(encoding="utf-8")
        block = re.search(
            r"^namespace " + re.escape(r["t_id"]) + r"\n(.*?)^end " + re.escape(r["t_id"]) + r"$",
            text,
            re.M | re.S,
        )
        assert block, r["t_id"]
        assert r["downgrade_noted"] == ("降级注" in block.group(1)), r["t_id"]
        assert r["full_statement_missing"] == ("完整陈述仍缺" in block.group(1)), r["t_id"]


def test_paper_quotes_the_derived_number() -> None:
    """Chapter 10 must not claim a FULL sweep the ledger does not support."""
    paper = PAPER_CN.read_text(encoding="utf-8")
    full = sum(
        1
        for r in _rows()
        if all(c["coverage"] == "FULL" for c in r["p_coverage"] if c["relation"] == "EXACT")
    )
    assert full == 0, "if targets were upgraded, update the paper wording deliberately"
    assert "127/127 全 COVERED" not in paper, "bare '127/127 COVERED' reads as theorem-level closure"
    assert re.search(r"127.*(定理级|GENERAL).{0,24}\(?(0|零)", paper) or "0/127" in paper or "一般式 0" in paper, (
        "chapter 10 must state how many T targets carry a general-form theorem"
    )
