import JurisLean.ULM16TheoryComposition

/-! Generated full ULM theorem/lemma axiom audit. Apply only after ULM01–16 elaborate. -/

#print axioms JurisLean.ULM.context_wf_iff
#print axioms JurisLean.ULM.preserves_id
#print axioms JurisLean.ULM.preserves_comp
#print axioms JurisLean.ULM.Outcome.map_complete
#print axioms JurisLean.ULM.Outcome.map_partial
#print axioms JurisLean.ULM.Outcome.map_failure
#print axioms JurisLean.ULM.Outcome.failure_ne_complete
#print axioms JurisLean.ULM.Outcome.partial_ne_complete
#print axioms JurisLean.ULM.Outcome.map_never_upgrades_failure
#print axioms JurisLean.ULM.applyEdge_request
#print axioms JurisLean.ULM.target_subset_applyEdge
#print axioms JurisLean.ULM.localTransition_preserves_request
#print axioms JurisLean.ULM.localTransition_has_declared_edge
#print axioms JurisLean.ULM.typeSafety_mem_required
#print axioms JurisLean.ULM.requiredObligations_nonempty
#print axioms JurisLean.ULM.sat_sound
#print axioms JurisLean.ULM.applyRunEdge_request
#print axioms JurisLean.ULM.applyRunEdge_marks_completed
#print axioms JurisLean.ULM.applied_edge_not_reenabled
#print axioms JurisLean.ULM.step_preserves_request
#print axioms JurisLean.ULM.run_preserves_request
#print axioms JurisLean.ULM.halted_has_no_step
#print axioms JurisLean.ULM.all_graph_edges_completed_quiescent
#print axioms JurisLean.ULM.tagPremise_request
#print axioms JurisLean.ULM.admitted_token_has_no_assumption
#print axioms JurisLean.ULM.assumed_token_keeps_assumption
#print axioms JurisLean.ULM.admitted_wf_has_admitted_status
#print axioms JurisLean.ULM.premise_origin_is_closed
#print axioms JurisLean.ULM.supportClosure_fixed
#print axioms JurisLean.ULM.supportClosure_least
#print axioms JurisLean.ULM.supportClosure_request_bound
#print axioms JurisLean.ULM.generated_candidate_sound
#print axioms JurisLean.ULM.generated_candidate_request_bound
#print axioms JurisLean.ULM.checkArgumentCoverage_sound
#print axioms JurisLean.ULM.checkArgumentCoverage_complete
#print axioms JurisLean.ULM.covered_argument_is_well_formed
#print axioms JurisLean.ULM.argument_supported_position_preserves_request
#print axioms JurisLean.ULM.argument_supported_position_preserves_claim
#print axioms JurisLean.ULM.argument_wf_has_well_founded_support
#print axioms JurisLean.ULM.argument_wf_has_no_dangling_edge
#print axioms JurisLean.ULM.mem_resolveDefeat_iff
#print axioms JurisLean.ULM.resolved_defeat_has_wf_source
#print axioms JurisLean.ULM.resolved_defeat_preserves_request
#print axioms JurisLean.ULM.queryRefutes_irreflexive
#print axioms JurisLean.ULM.attack_witness_required
#print axioms JurisLean.ULM.attack_preserves_request
#print axioms JurisLean.ULM.resolveToDefeatAF_wellFormed
#print axioms JurisLean.ULM.groundedExtension_fixed
#print axioms JurisLean.ULM.groundedExtension_least
#print axioms JurisLean.ULM.groundedExtension_subset_args
#print axioms JurisLean.ULM.groundedExtension_is_grounded
#print axioms JurisLean.ULM.grounded_unique
#print axioms JurisLean.ULM.empty_admissible
#print axioms JurisLean.ULM.admissibleFamily_nonempty
#print axioms JurisLean.ULM.exists_preferred
#print axioms JurisLean.ULM.mem_completeExtensions_iff
#print axioms JurisLean.ULM.mem_preferredExtensions_iff
#print axioms JurisLean.ULM.mem_stableExtensions_iff
#print axioms JurisLean.ULM.preferredExtensions_sound
#print axioms JurisLean.ULM.preferredExtensions_complete
#print axioms JurisLean.ULM.preferredExtensions_nonempty
#print axioms JurisLean.ULM.evaluateProfile_profile
#print axioms JurisLean.ULM.grounded_extension_family_nonempty
#print axioms JurisLean.ULM.preferred_extension_family_nonempty
#print axioms JurisLean.ULM.evaluateGrounded_profile
#print axioms JurisLean.ULM.evaluatePreferred_profile
#print axioms JurisLean.ULM.singleton_empty_family_nonempty
#print axioms JurisLean.ULM.different_branches_not_composable
#print axioms JurisLean.ULM.undecided_requires_enterable
#print axioms JurisLean.ULM.inconsistent_requires_acceptance_and_refutation
#print axioms JurisLean.ULM.enterability_has_positive_witness
#print axioms JurisLean.ULM.procedure_transition_preserves_normative_marker
#print axioms JurisLean.ULM.adjudicate_incomplete
#print axioms JurisLean.ULM.noExtension_without_authority_is_pending
#print axioms JurisLean.ULM.unmet_finding_uses_declared_failure
#print axioms JurisLean.ULM.procedural_disposition_precedes_entity_finding
#print axioms JurisLean.ULM.procedural_input_is_procedural
#print axioms JurisLean.ULM.burden_success_is_nonprocedural
#print axioms JurisLean.ULM.burden_failure_is_nonprocedural
#print axioms JurisLean.ULM.adjudicated_statuses_are_nonprocedural
#print axioms JurisLean.ULM.pending_ne_adjudicated
#print axioms JurisLean.ULM.solverIncomplete_ne_adjudicated
#print axioms JurisLean.ULM.compositionChoices_sound
#print axioms JurisLean.ULM.choice_wf_selected_subset
#print axioms JurisLean.ULM.choice_wf_policy_bound
#print axioms JurisLean.ULM.childOfChoice_selected
#print axioms JurisLean.ULM.childOfChoice_policy
#print axioms JurisLean.ULM.ExactExpr.eval_eq_denote
#print axioms JurisLean.ULM.exact_execution_matches_denotation
#print axioms JurisLean.ULM.incomplete_not_complete
#print axioms JurisLean.ULM.exemption_records_evidence
#print axioms JurisLean.ULM.trust_meet_le_left
#print axioms JurisLean.ULM.trust_meet_le_right
#print axioms JurisLean.ULM.combineSpec_open_left
#print axioms JurisLean.ULM.combineRunCheck_failed_left
#print axioms JurisLean.ULM.combineCoverage_open
#print axioms JurisLean.ULM.combineCoverage_notApplicable
#print axioms JurisLean.ULM.combineLegalInput_pendingRefs
#print axioms JurisLean.ULM.combineLegalInput_assumedRefs
#print axioms JurisLean.ULM.incompatible_assurance_scope_rejected
#print axioms JurisLean.ULM.combined_assurance_preserves_scope
#print axioms JurisLean.ULM.combined_open_spec_cannot_be_proved
#print axioms JurisLean.ULM.combined_coverage_retains_left_open
#print axioms JurisLean.ULM.combined_coverage_retains_left_exemptions
#print axioms JurisLean.ULM.combined_legal_input_retains_left_pending
#print axioms JurisLean.ULM.combined_assurance_retains_left_open_spec_refs
#print axioms JurisLean.ULM.combined_assurance_retains_left_notices
#print axioms JurisLean.ULM.TH_subset_extend
#print axioms JurisLean.ULM.horn_iter_subset_extend
#print axioms JurisLean.ULM.horn_closure_subset_extend
#print axioms JurisLean.ULM.incremental_correct_returns_full_recompute
#print axioms JurisLean.ULM.childFullRecompute_fixed
#print axioms JurisLean.ULM.empirical_is_read_only
#print axioms JurisLean.ULM.deviationScore_decomposes
#print axioms JurisLean.ULM.banach_exists_fixedPoint
#print axioms JurisLean.ULM.banach_fixedPoint_unique
#print axioms JurisLean.ULM.banach_iterates_converge
#print axioms JurisLean.ULM.banach_apriori_error_bound
#print axioms JurisLean.ULM.COMP_C01_trust_nonupgrade_left
#print axioms JurisLean.ULM.COMP_C01_trust_nonupgrade_right
#print axioms JurisLean.ULM.COMP_C02_observation_preservation
#print axioms JurisLean.ULM.COMP_C03_add_only_refinement
#print axioms JurisLean.ULM.COMP_C03_child_reference_fixed
#print axioms JurisLean.ULM.COMP_C04_failure_nonconversion
#print axioms JurisLean.ULM.CORE_01_typed_transition_request
#print axioms JurisLean.ULM.CORE_02_admitted_premise_status
#print axioms JurisLean.ULM.CORE_03_support_fixed
#print axioms JurisLean.ULM.CORE_04_generated_candidate_sound
#print axioms JurisLean.ULM.CORE_05_resolved_defeat_has_source
#print axioms JurisLean.ULM.CORE_07_resolved_bridge_wellFormed
#print axioms JurisLean.ULM.CORE_08_branch_nonmixing
#print axioms JurisLean.ULM.CORE_09_undecided_requires_enterable
#print axioms JurisLean.ULM.CORE_10_procedure_transition_nonmanufacture
#print axioms JurisLean.ULM.CORE_11_burden_failure_nonprocedural
#print axioms JurisLean.ULM.CORE_13_choice_membership
#print axioms JurisLean.ULM.CORE_14_exact_denotation
#print axioms JurisLean.ULM.CORE_15_empirical_read_only
#print axioms JurisLean.ULM.CORE_16_deviation_decomposition
#print axioms JurisLean.ULM.CORE_17_banach_exists
#print axioms JurisLean.ULM.CORE_19_argument_coverage_sound
#print axioms JurisLean.ULM.CORE_20_preferred_complete
#print axioms JurisLean.ULM.CORE_22_run_subject_preserved
#print axioms JurisLean.ULM.CORE_23_required_nonempty
#print axioms JurisLean.ULM.CORE_24_sat_sound
#print axioms JurisLean.ULM.CORE_25_incomplete_not_adjudicated
